### ISSUE TITLE
未ログイン時は投稿フォームを表示させないようにしたい

### ISSUE THREAD

**Issue by katsumata-ryo** [tetzng/music-reviews#14]
(ちらっと触らせていただいた、要望意見です！)

## 該当ページ

曲(tracks?)の詳細ページ

## 概要

未ログイン時にフォームが表示されていたので投稿してみた所ログインフォームに遷移したので
未ログイン時は投稿フォームを隠して「投稿するにはログインが必要です」的な文言を表示したい

## 備考

別案としては、投稿フォームは表示したままにしてPOSTする時にフロント側でログインの有無を確認し投稿はログインが必要な旨のモーダルをだしてあげて、
サインインorサインアップを促してページ遷移させるのもよさそう

## 解決したい課題

未ログイン状態と気づかず、熱い思いを込めたレビューがログイン画面に遷移したことで消えてしまうと2度と書く気がおこらない問題はありそうなので、未然に防ぐかコピーして一旦回避させる余地を残してあげたい。

**Comment by tetzng** [comment]
貴重なご意見ありがとうございます！
修正します！

**Comment by katsumata-ryo** [comment]
修正ありがとうございました！
PRを拝見してちょっとこれはおせっかいになってしまうので無視していただいても構いません！

たしかこのサービスはポートフォリオを兼ねていたかと思うんですが、
もしその視点が合ったのであれば、PRのコミットメッセージが 「Update ファイル名」や「Create ファイル名」となっているより なぜこの修正をしたのかがわかるコミットメッセージになっていると良いなと思いました。
ファイルを更新していることはファイルを見ればわかるのでPRをレビューする立場から見た時にこの修正はなぜ起こったのか何を変更すべきで変えたのかの情報がほしいなと思いました。
(自分も個人開発のときはコミットメッセージは雑になってしまうので、人と一緒にやるときにはされているのであれば全然問題有りません！)

あとこのコメントはサービスとは全く関係ないので消してもらって構いません！
修正が早くてびっくりしました！

**Comment by tetzng** [comment]
ご丁寧にありがとうございます。
お節介だなんてとんでもないです！

コミットメッセージに対しての意識やレビューする側の視点は欠落してましたので、今後は意識して改善します！
本当にありがとうございます！
